name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/dev' && 'development' || 'production' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            APP_DIR="${{ secrets.APP_DIR }}"
            BRANCH="${{ github.ref_name }}"
            PORT=3000
            APP_NAME="payment-gateway-main"

            if [ "$BRANCH" = "dev" ]; then
              PORT=3001
              APP_NAME="payment-gateway-dev"
            fi

            # Ensure the app directory exists
            mkdir -p $APP_DIR

            # Navigate to the app directory
            cd $APP_DIR

            # Pull latest code
            git fetch origin $BRANCH
            git reset --hard origin/$BRANCH

            # Install dependencies
            npm install --production

            # Build the application
            npm run build

            # Start or restart app using PM2
            pm2 delete $APP_NAME || true
            pm2 start npm --name $APP_NAME -- start -- -p $PORT

            # Save PM2 process list
            pm2 save

            echo "Deployment complete for branch $BRANCH on port $PORT"
